<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3889" started-at="2017-01-17T03:10:31Z" finished-at="2017-01-17T03:10:34Z">
    <groups>
    </groups>
    <test name="mycourse03" duration-ms="3889" started-at="2017-01-17T03:10:31Z" finished-at="2017-01-17T03:10:34Z">
      <class name="com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test">
        <test-method status="PASS" signature="beforeTest(org.testng.ITestContext)[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="beforeTest" is-config="true" duration-ms="60" started-at="2017-01-17T11:10:31Z" finished-at="2017-01-17T11:10:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2794eab6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="startTest(org.testng.ITestContext)[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="startTest" is-config="true" duration-ms="602" started-at="2017-01-17T11:10:31Z" finished-at="2017-01-17T11:10:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2794eab6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="PASS" signature="testCase(java.util.Map)[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="testCase" duration-ms="1145" started-at="2017-01-17T11:10:31Z" data-provider="testData" finished-at="2017-01-17T11:10:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expect=false, msgId=msgId:20003, json=subjectId:null,termId:null,memberId:{memberId}, mobileno=13900000001}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
        <test-method status="PASS" signature="testCase(java.util.Map)[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="testCase" duration-ms="685" started-at="2017-01-17T11:10:33Z" data-provider="testData" finished-at="2017-01-17T11:10:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expect=false, msgId=msgId:20003, json=subjectId:0,termId:null, mobileno=13900000001}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
        <test-method status="FAIL" signature="testCase(java.util.Map)[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="testCase" duration-ms="625" started-at="2017-01-17T11:10:33Z" data-provider="testData" finished-at="2017-01-17T11:10:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expect=true, msgId=msgId:20003, json=subjectId:0,termId:0, mobileno=13900000001}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.mistong.interfacetest.util.UnirestUtil.InterfaceTest(UnirestUtil.java:66)
	at com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test.testCase(mycourse_003_getCurrentList_test.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
        <test-method status="FAIL" signature="testCase(java.util.Map)[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="testCase" duration-ms="610" started-at="2017-01-17T11:10:34Z" data-provider="testData" finished-at="2017-01-17T11:10:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{expect=true, msgId=msgId:20003, json=subjectId:0,termId:0,memberId:{memberId}, mobileno=13900000001}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.mistong.interfacetest.util.UnirestUtil.InterfaceTest(UnirestUtil.java:66)
	at com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test.testCase(mycourse_003_getCurrentList_test.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="endTest" is-config="true" duration-ms="1" started-at="2017-01-17T11:10:34Z" finished-at="2017-01-17T11:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test@604ed9f0]" name="AfterTest" is-config="true" duration-ms="1" started-at="2017-01-17T11:10:34Z" finished-at="2017-01-17T11:10:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- com.mistong.interfacetest.testcases.mycourse.mycourse_003_getCurrentList_test -->
    </test> <!-- mycourse03 -->
  </suite> <!-- Suite -->
</testng-results>
